### ISSUE TITLE
Users can click Authorize without entering Credentials

### ISSUE THREAD

**Issue by DeeKoy** [kbeflo/evilportals#9]
I've noticed that in some cases users will click authorize without entering credentials and be added to the authorized list. My suggestion would be to make these fields required. Do you want me to initiate a pull request?

**Comment by DeeKoy** [comment]
What's interesting is I see the "required" tag; however it's still possible to click through... Maybe the placeholder is messing this up. I will investigate later when I get home.

**Comment by kbeflo** [comment]
Was expecting your reply for 174 days, when will you ever get home?

Closing thread, I'll re-open issue if necessary.

**Comment by zerocolTHS** [comment]
I am having the same issue, every portal I try if they wait portal just disappears. Also there isn't even enough time to input anything.

**Comment by zerocolTHS** [comment]
Why was this closed/

**Comment by kbeflo** [comment]
This was due to https requests going trough the pineapple ignoring the portal. Update and try again.

**Comment by H4xl0r** [comment]
please close should be fixed ?

**Comment by zerocolTHS** [comment]
This reply is after so I'm guessing this still isn't fixed OR is it>? 
kbefloLast Wednesday at 3:03 AM
I tested on multiple smart phones some still bypass the iptable rules on the module resulting in the portals not showing up.

**Comment by H4xl0r** [comment]
would be interesting to see how they are able to bypass that iptables.
Do they use ip6 ? 
Could you Burp (Burpsuite / proxy) the traffic, so we can fix this ? 
my devices are all getting blocked! Iphone and android , but could be firmware or something.
would be helpful to get a real info , like what going on there .
(Burpsuite traffic )
